#ifndef GLCOMPUTES2_GLOBAL_HPP
#define GLCOMPUTES2_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(GLCOMPUTES2_LIBRARY)
#  define GLCOMPUTES2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLCOMPUTES2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLCOMPUTES2_GLOBAL_HPP
